// Generated by CoffeeScript 1.9.3
rcmail.addEventListener('contextmenu_init', function(menu) {
  if (menu.menu_name === 'messagelist') {
    menu.addEventListener('init', function(p) {
      var labels;
      if (p.ref.menu_name === 'tb_label_popup') {
        $(p.ref.container).children('ul').remove();
        labels = $('#tb_label_popup ul').clone();
        $(labels).find('a').click(function(ev) {
          var prev_display_next, prev_sel;
          if (p.ref.list_object) {
            prev_display_next = rcmail.env.display_next;
            if (!(p.ref.list_object.selection.length === 1 && p.ref.list_object.in_selection(rcmail.env.context_menu_source_id))) {
              rcmail.env.display_next = false;
            }
            prev_sel = p.ref.list_selection(true);
          }
          rcm_tb_label_onclick($(ev.target));
          if (p.ref.list_object) {
            p.ref.list_selection(false, prev_sel);
            rcmail.env.display_next = prev_display_next;
          }
        });
      }
      $(p.ref.container).append(labels);
    });
    menu.addEventListener('activate', function(p) {
      var ref;
      if (p.btn === 'tb') {
        if (!$(p.el).parent('li').hasClass('submenu')) {
          ref = rcmail.env.contextmenus['messagelist'];
          $(p.el).parent('li').addClass('submenu');
          $(p.el).append("<span class='right-arrow'></span>");
          $(p.el).data('command', 'tb_label_popup');
          $(p.el).unbind('click');
          $(p.el).click(function(e) {
            if (!$(this).hasClass('active')) {
              return;
            }
            ref.submenu(this, e);
            return false;
          });
          if (ref.mouseover_timeout > -1) {
            $(p.el).mouseover(function(e) {
              if (!$(this).hasClass('active')) {
                return;
              }
              ref.timers['submenu_show'] = window.setTimeout(function(a, e) {
                ref.submenu(a, e);
              }, ref.mouseover_timeout, $(p.el), e);
            });
            $(p.el).mouseout(function(e) {
              $(this).blur();
              clearTimeout(ref.timers['submenu_show']);
            });
          }
        }
        $(p.el).parent('li').show();
        return rcmail.commands['plugin.thunderbird_labels.rcm_tb_label_submenu'];
      }
    });
  }
});
