<?php
/**
* Author:
* soufien88y
*/

$labels = array();
$labels['label'] = 'وسوم ثندربيرد ';
$labels['label0'] = 'وسم مفتوح';
$labels['label1'] = 'هام';
$labels['label2'] = 'عمل';
$labels['label3'] = 'موظفون';
$labels['label4'] = 'أداء';
$labels['label5'] = 'أخيرًا';

$labels['tb_label_options'] = 'خيارات وسوم ثندربيرد';
$labels['tb_label_enable_option'] = 'تفعيل الوسوم';
$labels['tb_label_enable_shortcuts_option'] = 'تفعيل لوحة المفاتيح المختصرة';
$labels['tb_label_button_label'] = 'الوسوم';
$labels['tb_label_button_title'] = 'تفعيل الوسوم في الرسائل';
$labels['tb_label_contextmenu_title'] = 'الوسوم';
$labels['tb_label_style_option'] = 'النمط الرسومي';
$labels['tb_label_label'] = "وسم";
