<?php
/**
* Author:
* Daniel Johansson - LANTECH
*/

$labels = array();
$labels['label'] = 'Färgmärkering';
$labels['label0'] = 'Ingen färg';
$labels['label1'] = '1 - Viktigt';
$labels['label2'] = '2 - Att göra';
$labels['label3'] = '3 - Klar';
$labels['label4'] = '4 - Under arbete';
$labels['label5'] = '5 - Annat';

$labels['tb_label_options'] = 'Färgmärknings alternativ';
$labels['tb_label_enable_option'] = 'Aktivera etiketter';
$labels['tb_label_enable_shortcuts_option'] = 'Aktivera tangentbordsgenvägar';
$labels['tb_label_button_label'] = 'Färgmarkera';
$labels['tb_label_button_title'] = 'Sätt etikett';
$labels['tb_label_contextmenu_title'] = 'Etiketter';
$labels['tb_label_style_option'] = "Utseende för färgmarkering";
$labels['tb_label_label'] = "Etikett";

$messages = array();

