<?php
/**
* Author:
* Michael Kefeder
* http://code.google.com/p/rcmail-thunderbird-labels/
*/

$labels = array();
$labels['label'] = 'Thunderbird Schlagwörter';
$labels['label0'] = 'Alle Entfernen';
$labels['label1'] = 'Wichtig';
$labels['label2'] = 'Dienstlich';
$labels['label3'] = 'Persönlich'; // grün
$labels['label4'] = 'Zu Erledigen'; // blau
$labels['label5'] = 'Später';

$messages = array();

